version: '2'
services:
  nodered:
    build: ./nodered
    #depends_on:
    #  - influxdb
    #  - mosquitto
    volumes:
      - "nodered:/var/lib/node-red"
    expose:
      - "80"
    ports:
      - 80:80
    #devices:
    #  - "/dev/i2c-1:/dev/i2c-1"
    #  - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
  couchdb:
    image: couchdb
    hostname: couchdb.server
    volumes:
      - "couchdb:/var/lib/couchdb"    
    ports:
      - 5984:5984
      - 4369:4369
      - 9100:9100
    expose:
      - "5984"

volumes:
  nodered:
  couchdb:
  